In [ ]:
"""
        1.Series对象构建
        2.pandas日期处理

"""

In [1]:
"""
    - Series对象
        - 创建Series对象
            - pd.Series()

"""
import pandas as pd
import numpy as np
s = pd.Series()
print(s,type(s),s.dtype)

#通过ndarray创建Series对象
array = np.array([1,2,3,4,5])
s = pd.Series(array)
print(s)
#创建Series对象时，指定index行级索引标签
s = pd.Series(array,index=["a","b","c","d","e"])
print(s["a"])
#从字典创建一个系列
dic = {"a":1,"b":2,"c":3}
s = pd.Series(dic)
print(s)

#从标创建Series
s = pd.Series(5,index=["a","b","c"])
print(s)

#访问Series中的数据
#使用索引检索数据
print(s[0])
print(s[:2])
print(s["a"])
print(s["c"])
print(s[["a","c"]])

Series([], dtype: float64) <class 'pandas.core.series.Series'> float64
0    1
1    2
2    3
3    4
4    5
dtype: int32
1
a    1
b    2
c    3
dtype: int64
a    5
b    5
c    5
dtype: int64
5
a    5
b    5
dtype: int64
5
5
a    5
c    5
dtype: int64

D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if __name__ == '__main__':

In [17]:
"""
    - pandas日期处理
        - pd.to_datetime([dates]) 转换日期数据类型
        - timedelta64[ns]类型时
            - timedelta.dt.days          获取天数
            - timedelta.dt.seconds       获取秒数
        - datetime64[ns]类型时
            - datetime.dt.year                  年份
            - datetime.dt.month                 月份
            - datetime.dt.days                  天数
            - datetime.dt.hour                  小时
            - datetime.dt.minute                分钟
            - datetime.dt.second                秒数
            - datetime.dt.microsecond           微秒数
            - datetime.dt.week                  一年中第几周。
            - datetime.dt.weekofyear            一年中第几周。
            - datetime.dt.dayofweek             一周内的星期数,范围：Monday=0, Sunday=6。
            - datetime.dt.weekday               一周内的星期数,范围：Monday=0, Sunday=6。
            - datetime.dt.dayofyear             一年中的第几天
            - datetime.dt.quarter               一年中的季度
            - datetime.dt.is_month_start        日期是否为每月的第一天
            - datetime.dt.is_month_end          日期是否为该月的最后一天
            - datetime.dt.is_quarter_start      日期是否为一个季度的第一天。
            - datetime.dt.is_quarter_end        日期是否为一个季度的最后一天
            - datetime.dt.is_year_start         日期是否为一年的第一天。
            - datetime.dt.is_leap_year          日期是否属于闰年
            - datetime.dt.days_in_month         一个月中的天数
    - DateTimeIndex
            - date_range(start=None,end=None,periods=None,freq=None,tz=None)
                - start                         开始日期
                - end                           结束日期
                - periods                       要生成的周期数。
                - freq                          默认频率为D[天],可选参数M(月份)

"""
import pandas as pd

dates = pd.Series(["2011","2011-02","2011-03-01","2011/04/01","2011/05/01 01:01:01","01Jun 2011"])
dates = pd.to_datetime(dates)
# print(dates,type(dates),dates.dtype)
# datetime类型数据支持日期运算
delta = dates - pd.to_datetime('2010-01-01')  #日期偏移量
# 获取天数数值
# print(delta.dt.days)
# 获取秒数数值
# print(delta.dt.seconds)


# print(dates.dtype,66)   #datetime64[ns]
# print(delta.dtype)      #timedelta64[ns]
#
print(dates.dt.year)
print(dates.dt.month)
print(dates.dt.day)
print(dates.dt.hour)
print(dates.dt.minute)
print(dates.dt.second)
print(dates.dt.microsecond)
print(dates.dt.week)
print(dates.dt.weekday)
print(dates.dt.dayofweek)
print(dates.dt.quarter)

print(dates.dt.is_month_start)
print(dates.dt.is_year_end)
print(dates.dt.is_leap_year)
print(dates.dt.days_in_month)

# 以日为频率
datelist = pd.date_range('2019/08/21', periods=5)
print(datelist)
# 以月为频率
datelist = pd.date_range('2019/08/21', periods=5,freq='M')
print(datelist)
# 构建某个区间的时间序列
start = pd.datetime(2017, 11, 1)
end = pd.datetime(2017, 11, 5)
dates = pd.date_range(start, end,periods=7)
print(dates)
 #修改频率为M
dates = pd.date_range("2021/01/01",periods=7,freq="M")
print(dates)
#生成时间序列(工作日时间序列)
dates = pd.bdate_range("2021/1/1",periods=7) #跳过周六日
print(dates)

0    2011
1    2011
2    2011
3    2011
4    2011
5    2011
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
0    1
1    1
2    1
3    1
4    1
5    1
dtype: int64
0    0
1    0
2    0
3    0
4    1
5    0
dtype: int64
0    0
1    0
2    0
3    0
4    1
5    0
dtype: int64
0    0
1    0
2    0
3    0
4    1
5    0
dtype: int64
0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64
0    52
1     5
2     9
3    13
4    17
5    22
dtype: int64
0    5
1    1
2    1
3    4
4    6
5    2
dtype: int64
0    5
1    1
2    1
3    4
4    6
5    2
dtype: int64
0    1
1    1
2    1
3    2
4    2
5    2
dtype: int64
0    True
1    True
2    True
3    True
4    True
5    True
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
0    31
1    28
2    31
3    30
4    31
5    30
dtype: int64
DatetimeIndex(['2019-08-21', '2019-08-22', '2019-08-23', '2019-08-24',
               '2019-08-25'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30',
               '2019-12-31'],
              dtype='datetime64[ns]', freq='M')
DatetimeIndex(['2017-11-01 00:00:00', '2017-11-01 16:00:00',
               '2017-11-02 08:00:00', '2017-11-03 00:00:00',
               '2017-11-03 16:00:00', '2017-11-04 08:00:00',
               '2017-11-05 00:00:00'],
              dtype='datetime64[ns]', freq=None)
DatetimeIndex(['2021-01-31', '2021-02-28', '2021-03-31', '2021-04-30',
               '2021-05-31', '2021-06-30', '2021-07-31'],
              dtype='datetime64[ns]', freq='M')
DatetimeIndex(['2021-01-01', '2021-01-04', '2021-01-05', '2021-01-06',
               '2021-01-07', '2021-01-08', '2021-01-11'],
              dtype='datetime64[ns]', freq='B')

D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:68: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:86: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

In [47]:
"""
    DataFrame
        - DataFrame是一个类似于表格的数据类型，可以理解为一个二维数组，索引有两个维度，可更改。DataFrame具有以下特点：
            - 潜在的列是不同的类型
            - 大小可变
            - 标记轴(行和列)
            - 可以对行和列执行算术运算
        - np.DataFrame()
        创建方式:
            - 通过列表创建
                - 一位列表:[](生成一列数据)
                - 二维列表:[[],[],...](生成二维行列数据,取最长长度的一位列表为二维列数)
                - 二维列表:[{},{},...](生成二维行列数据,取最长长度的字典为二维列数)
            - 通过字典创建
                - 二维字典:{"key1":[],"key2":[],....}
                - 二维字典:{"key1":Series,"key2":Series,....}






"""
import pandas as pd
import numpy as np
df = pd.DataFrame()
# df
# 通过列表创建DataFrame

data = [["Tom",13],["Jack",11],["Andy",20]]
df = pd.DataFrame(data,index=[chr(i) for i in range(97,100)])
print(df)
print("*"*30)

data = np.arange(1,9)
df = pd.DataFrame(data)
print(df)

print("*"*30)

#通过字典创建DataFrame
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10,"c":20}]
df = pd.DataFrame(data)
print(df)

print("*"*30)

data = {'a': 5, 'b': 10,"c":20}
df = pd.DataFrame(data,index=[0])
print(df)
print("*"*30)

data = {"name":['Tom',"Jack","Andy"],"age":[20,17,30]}
df = pd.DataFrame(data)
print(df)
print("*"*30)
data = {"one":pd.Series([1,2,3],index=['a','b','c']),"two":pd.Series([7,8,9,10],index=['a','b','c','d'])}
df = pd.DataFrame(data)
print(df)

      0   1
a   Tom  13
b  Jack  11
c  Andy  20
******************************
   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
******************************
   a   b     c
0  1   2   NaN
1  5  10  20.0
******************************
   a   b   c
0  5  10  20
******************************
   name  age
0   Tom   20
1  Jack   17
2  Andy   30
******************************
   one  two
a  1.0    7
b  2.0    8
c  3.0    9
d  NaN   10

In [90]:
"""
    DataFrame操作
        - df.index                  拿到所有的行级索引标签
        - df.columns                拿到所有的列级索引标签
        - df.copy(deep)             复制DataFrame数据，默认deep为True，深拷贝
        - df.loc["索引名"]           获得行索引数据,索引名为index
        - df.iloc["索引下标"]         获得行索引数据,索引名为index
        - df.append(DataFrame)      添加行数据,并返回一个新的DataFrame,不改变原DataFrame数据
        - df.drop(index)            根据行索引名删除行数据,并返回一个新的DataFrame,不改变原DataFrame数据
"""
import pandas as pd
data = {"one":pd.Series([1,2,3],index=['a','b','c']),"two":pd.Series([7,8,9,10],index=['a','b','c','d'])}
df = pd.DataFrame(data)
print(df)
'''列操作'''
#按列索引
print(df["one"])
print(df[["one","two"]])
print("*"*30)

#添加列数据(不写index,则全部是NaN)
df["three"] = pd.Series([1,2,3,7],index=["a",'b','c','d'])
df["three"] = pd.Series([1,2,3,7],index=df.index)
print(df)
print("*"*30)

#删除列数据
df.pop("one")
del df["two"]
print(df)
print("*"*30)

#修改列数据
df["three"] = pd.Series([4,6,7,9],index=df.index)
print(df)
print("*"*30)

'''行操作'''
data = {"one":pd.Series([1,2,3],index=['a','b','c']),"two":pd.Series([7,8,9,10],index=['a','b','c','d'])}
df = pd.DataFrame(data)
#按切片行索引
print(df)
print(df[0:2])

#按索引名获取行数据
print(df.loc["a"])
print(df.loc[["a","c"]])

#按索引获取行数据
print(df.iloc[2])
print(df.iloc[[0,3]])
print(df.iloc[0,0])     #获得标量数据
#行添加
row_data = {"one":[2],"two":[5]}
df2 = pd.DataFrame(row_data,index=["e"])

df = df.append(df2)
df
#行删除
print("*"*30)
print(df.drop("d"))
#修改行数据
print("*"*30)
df["one"][0] = 3
df

   one  two
a  1.0    7
b  2.0    8
c  3.0    9
d  NaN   10
a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
   one  two
a  1.0    7
b  2.0    8
c  3.0    9
d  NaN   10
******************************
   one  two  three
a  1.0    7      1
b  2.0    8      2
c  3.0    9      3
d  NaN   10      7
******************************
   three
a      1
b      2
c      3
d      7
******************************
   three
a      4
b      6
c      7
d      9
******************************
   one  two
a  1.0    7
b  2.0    8
c  3.0    9
d  NaN   10
   one  two
a  1.0    7
b  2.0    8
one    1.0
two    7.0
Name: a, dtype: float64
   one  two
a  1.0    7
c  3.0    9
one    3.0
two    9.0
Name: c, dtype: float64
   one  two
a  1.0    7
d  NaN   10
1.0
******************************
   one  two
a  1.0    7
b  2.0    8
c  3.0    9
e  2.0    5
******************************

D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   one  two
a  3.0    7
b  2.0    8
c  3.0    9
d  NaN   10
e  2.0    5

In [103]:
"""
    DataFrame常用属性
       - axes                       返回 行/列 标签（index）列表
       - dtype                      返回对象的数据类型(dtype)。
       - dtypes                     返回DataFrame的数据类型(dtype)。
       - empty                      如果系列为空，则返回True
       - ndim                       返回底层数据的维度，默认定义:1
       - size                       返回基础数据中的元素数
       - values                     将系数作为ndarray返回
       - head()                     返回前n行
       - tail()                     返回最后n行

"""
import pandas as pd
data = {"name":["Tom",'Jack',"Steve","Ricky"],"age":[20,23,21,26]}
df = pd.DataFrame(data,index=['s1','s2','s3','s4'])
print(df.axes)
print(df.dtypes,df["name"].dtype)
print(df.empty)
print(df.ndim)
print(df.size)
print(df.values)
print(df.head(2))
print(df.tail(2))

[Index(['s1', 's2', 's3', 's4'], dtype='object'), Index(['name', 'age'], dtype='object')]
name    object
age      int64
dtype: object object
False
2
8
[['Tom' 20]
 ['Jack' 23]
 ['Steve' 21]
 ['Ricky' 26]]
    name  age
s1   Tom   20
s2  Jack   23
     name  age
s3  Steve   21
s4  Ricky   26

In [121]:
"""
    pandas描述性统计
        数值型数据的描述性统计主要包括了计算数值型数据的完整情况、最小值、均值、中位 数、最大值、四分位数、极差、标准差、方差、
        协方差等。在NumPy库中一些常用的统计学函数也可用于对数据框进行描述性统计。
        - df.count()                                非空观测数量
        - df.sum(axis=None)                         所有值之和
        - df.mean(axis=None)                        所有值的平均值
        - df.median(axis=None)                      所有值的中位数
        - df.std(axis=None)                         值的标准偏差
        - df.min(axis=None)                         所有值中的最小值
        - df.max(axis=None)                         所有值中的最大值
        - df.abs(axis=None)                         绝对值
        - df.prod(axis=None)                        数组元素的乘积
        - df.cumsum(axis=None)                      累计总和
        - df.cumprod(axis=None)                     累计乘积
        - df.describe(include)                      拿到所有统计数据(如果为number,拿到所有数值型数据,如果为object,则拿到所有字符型数据)



"""
import pandas as pd
# 创建DataFrame
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Minsu','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])}

df = pd.DataFrame(d)
print(df)
print(df.count())
print(df.sum())
print(df.mean())
print(df.median())
print(df.std())
print(df.min())
print(df.max())
print(df[["Age","Rating"]].abs())
print(df.prod())
print(df.cumsum())
print(df[["Age","Rating"]].cumprod())
print(df.describe())

      Name  Age  Rating
0      Tom   25    4.23
1    James   26    3.24
2    Ricky   25    3.98
3      Vin   23    2.56
4    Steve   30    3.20
5    Minsu   29    4.60
6     Jack   23    3.80
7      Lee   34    3.78
8    David   40    2.98
9   Gasper   30    4.80
10  Betina   51    4.10
11  Andres   46    3.65
Name      12
Age       12
Rating    12
dtype: int64
Name      TomJamesRickyVinSteveMinsuJackLeeDavidGasperBe...
Age                                                     382
Rating                                                44.92
dtype: object
Age       31.833333
Rating     3.743333
dtype: float64
Age       29.50
Rating     3.79
dtype: float64
Age       9.232682
Rating    0.661628
dtype: float64
Name      Andres
Age           23
Rating      2.56
dtype: object
Name      Vin
Age        51
Rating    4.8
dtype: object
    Age  Rating
0    25    4.23
1    26    3.24
2    25    3.98
3    23    2.56
4    30    3.20
5    29    4.60
6    23    3.80
7    34    3.78
8    40    2.98
9    30    4.80
10   51    4.10
11   46    3.65
Age       7.158408e+17
Rating    6.320128e+06
dtype: float64
                                                 Name  Age  Rating
0                                                 Tom   25    4.23
1                                            TomJames   51    7.47
2                                       TomJamesRicky   76   11.45
3                                    TomJamesRickyVin   99   14.01
4                               TomJamesRickyVinSteve  129   17.21
5                          TomJamesRickyVinSteveMinsu  158   21.81
6                      TomJamesRickyVinSteveMinsuJack  181   25.61
7                   TomJamesRickyVinSteveMinsuJackLee  215   29.39
8              TomJamesRickyVinSteveMinsuJackLeeDavid  255   32.37
9        TomJamesRickyVinSteveMinsuJackLeeDavidGasper  285   37.17
10  TomJamesRickyVinSteveMinsuJackLeeDavidGasperBe...  336   41.27
11  TomJamesRickyVinSteveMinsuJackLeeDavidGasperBe...  382   44.92
                   Age        Rating
0                   25  4.230000e+00
1                  650  1.370520e+01
2                16250  5.454670e+01
3               373750  1.396395e+02
4             11212500  4.468465e+02
5            325162500  2.055494e+03
6           7478737500  7.810877e+03
7         254277075000  2.952512e+04
8       10171083000000  8.798485e+04
9      305132490000000  4.223273e+05
10   15561756990000000  1.731542e+06
11  715840821540000000  6.320128e+06
             Age     Rating
count  12.000000  12.000000
mean   31.833333   3.743333
std     9.232682   0.661628
min    23.000000   2.560000
25%    25.000000   3.230000
50%    29.500000   3.790000
75%    35.500000   4.132500
max    51.000000   4.800000

D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:31: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:32: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:33: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
D:\PycharmProjects\dataAnalysis\venv\lib\site-packages\ipykernel_launcher.py:37: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

In [128]:
"""
    pandas排序
        - pandas有两种排序方式，它们分别是按标签与按实际值排序。
            - 按标签排序
                - df.sort_index(axis,ascending）
                    - axis                          0:按行排序 1:按列排序
                    - ascending                     True:升序 False:降序
            - 按实际值排序
                - df.sort_values(by)
                    - by                            指定具体的标签名
                    - ascending                     True:升序 False:降序

"""

import pandas as pd
d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Minsu','Jack',
   'Lee','David','Gasper','Betina','Andres']),
   'Age':pd.Series([25,26,25,23,30,29,23,34,40,30,51,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])}
unsorted_df = pd.DataFrame(d)
#按行标签排序
print(unsorted_df.sort_index(ascending=False))
#按列标签排序
print(unsorted_df.sort_index(axis=1))

#按实际值排序
print(unsorted_df.sort_values(by="Age"))
print(unsorted_df.sort_values(by=["Age","Rating"],ascending=[True,False]))

      Name  Age  Rating
11  Andres   46    3.65
10  Betina   51    4.10
9   Gasper   30    4.80
8    David   40    2.98
7      Lee   34    3.78
6     Jack   23    3.80
5    Minsu   29    4.60
4    Steve   30    3.20
3      Vin   23    2.56
2    Ricky   25    3.98
1    James   26    3.24
0      Tom   25    4.23
    Age    Name  Rating
0    25     Tom    4.23
1    26   James    3.24
2    25   Ricky    3.98
3    23     Vin    2.56
4    30   Steve    3.20
5    29   Minsu    4.60
6    23    Jack    3.80
7    34     Lee    3.78
8    40   David    2.98
9    30  Gasper    4.80
10   51  Betina    4.10
11   46  Andres    3.65
      Name  Age  Rating
3      Vin   23    2.56
6     Jack   23    3.80
0      Tom   25    4.23
2    Ricky   25    3.98
1    James   26    3.24
5    Minsu   29    4.60
4    Steve   30    3.20
9   Gasper   30    4.80
7      Lee   34    3.78
8    David   40    2.98
11  Andres   46    3.65
10  Betina   51    4.10
      Name  Age  Rating
6     Jack   23    3.80
3      Vin   23    2.56
0      Tom   25    4.23
2    Ricky   25    3.98
1    James   26    3.24
5    Minsu   29    4.60
9   Gasper   30    4.80
4    Steve   30    3.20
7      Lee   34    3.78
8    David   40    2.98
11  Andres   46    3.65
10  Betina   51    4.10